[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
evm_version = "paris" # Needed to deploy on chains that don't support PUSH0 (e.g. Optimism, Arbitrum)
via-ir = true
optimizer-runs = 1
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts",
  "openzeppelin-contracts/contracts=lib/openzeppelin-contracts/contracts/",
  "@chainlink/=lib/chainlink/",
  "solmate/=lib/solmate/src/",
  "cozy-safety-module-models/=lib/cozy-safety-module-models/src",
  "cozy-safety-module-triggers/=lib/cozy-safety-module-triggers",
  "cozy-safety-module-shared/=lib/cozy-safety-module-shared/src",
  "cozy-safety-module-rewards-manager/=lib/cozy-safety-module-rewards-manager/src",
]
fs_permissions = [{ access = "read", path = "./script/input"}]

[profile.default.fuzz]
runs = 1024

[profile.lite]
optimizer = false # Speed up compilation for faster builds.
via-ir = false # Speed up compilation for faster builds.

[profile.default.fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = true
ignore = [
  "src/lib/ERC20.sol",
  "src/lib/PackedStringLib.sol",
  "src/lib/SafeERC20.sol"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
